---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - s3.bedag.ch
  resources:
  - globals3policies
  - s3accesses
  - s3buckets
  - s3policies
  - s3tenantaccounts
  - s3tenantclasses
  - s3tenants
  - storagegrids
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - s3.bedag.ch
  resources:
  - globals3policies/finalizers
  - s3accesses/finalizers
  - s3buckets/finalizers
  - s3policies/finalizers
  - s3tenantaccounts/finalizers
  - s3tenantclasses/finalizers
  - s3tenants/finalizers
  - storagegrids/finalizers
  verbs:
  - update
- apiGroups:
  - s3.bedag.ch
  resources:
  - globals3policies/status
  - s3accesses/status
  - s3buckets/status
  - s3policies/status
  - s3tenantaccounts/status
  - s3tenantclasses/status
  - s3tenants/status
  - storagegrids/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - s3.bedag.ch
  resources:
  - s3tenantaccountss
  verbs:
  - get
  - list
  - watch
