# permissions for end users to view s3tenantaccounts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: storagegrid-operator
    app.kubernetes.io/managed-by: kustomize
  name: s3tenantaccount-viewer-role
rules:
- apiGroups:
  - s3.bedag.ch
  resources:
  - s3tenantaccounts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - s3.bedag.ch
  resources:
  - s3tenantaccounts/status
  verbs:
  - get
