apiVersion: s3.bedag.ch/v1alpha1
kind: S3TenantAccount
metadata:
  labels:
    app.kubernetes.io/name: storagegrid-operator
    app.kubernetes.io/managed-by: kustomize
  name: s3tenantaccount-sample
spec:
  storageGridRef:
    name: primary-grid
  name: jle-test
  defaultBucketRegion: ch-bern-1
  description: Test S3 Tenant
  s3TenantClassName: itpfe
  storageQuota: 6Gi
