//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BucketDrainStatus) DeepCopyInto(out *BucketDrainStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.LastCheckedAt != nil {
		in, out := &in.LastCheckedAt, &out.LastCheckedAt
		*out = (*in).DeepCopy()
	}
	if in.LastProgressAt != nil {
		in, out := &in.LastProgressAt, &out.LastProgressAt
		*out = (*in).DeepCopy()
	}
	out.NextPollInterval = in.NextPollInterval
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BucketDrainStatus.
func (in *BucketDrainStatus) DeepCopy() *BucketDrainStatus {
	if in == nil {
		return nil
	}
	out := new(BucketDrainStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BucketUsage) DeepCopyInto(out *BucketUsage) {
	*out = *in
	if in.Bytes != nil {
		in, out := &in.Bytes, &out.Bytes
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BucketUsage.
func (in *BucketUsage) DeepCopy() *BucketUsage {
	if in == nil {
		return nil
	}
	out := new(BucketUsage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonTenantSpec) DeepCopyInto(out *CommonTenantSpec) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.AdditionalTenantMetadata != nil {
		in, out := &in.AdditionalTenantMetadata, &out.AdditionalTenantMetadata
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.AllowedNamespaces != nil {
		in, out := &in.AllowedNamespaces, &out.AllowedNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DefaultBucketRegion != nil {
		in, out := &in.DefaultBucketRegion, &out.DefaultBucketRegion
		*out = new(string)
		**out = **in
	}
	if in.AdminSecretRef != nil {
		in, out := &in.AdminSecretRef, &out.AdminSecretRef
		*out = new(corev1.ObjectReference)
		**out = **in
	}
	if in.S3AdminKeysSecretRef != nil {
		in, out := &in.S3AdminKeysSecretRef, &out.S3AdminKeysSecretRef
		*out = new(corev1.ObjectReference)
		**out = **in
	}
	if in.StorageQuota != nil {
		in, out := &in.StorageQuota, &out.StorageQuota
		x := (*in).DeepCopy()
		*out = &x
	}
	out.StorageGridRef = in.StorageGridRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonTenantSpec.
func (in *CommonTenantSpec) DeepCopy() *CommonTenantSpec {
	if in == nil {
		return nil
	}
	out := new(CommonTenantSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonTenantStatus) DeepCopyInto(out *CommonTenantStatus) {
	*out = *in
	in.Quota.DeepCopyInto(&out.Quota)
	if in.Regions != nil {
		in, out := &in.Regions, &out.Regions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.TenantUsage = in.TenantUsage
	if in.AdminSecretRef != nil {
		in, out := &in.AdminSecretRef, &out.AdminSecretRef
		*out = new(corev1.ObjectReference)
		**out = **in
	}
	if in.S3AdminKeysSecretRef != nil {
		in, out := &in.S3AdminKeysSecretRef, &out.S3AdminKeysSecretRef
		*out = new(corev1.ObjectReference)
		**out = **in
	}
	if in.S3EndpointConfig != nil {
		in, out := &in.S3EndpointConfig, &out.S3EndpointConfig
		*out = new(S3EndpointConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonTenantStatus.
func (in *CommonTenantStatus) DeepCopy() *CommonTenantStatus {
	if in == nil {
		return nil
	}
	out := new(CommonTenantStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DrainConfig) DeepCopyInto(out *DrainConfig) {
	*out = *in
	if in.InitialPollInterval != nil {
		in, out := &in.InitialPollInterval, &out.InitialPollInterval
		*out = new(v1.Duration)
		**out = **in
	}
	if in.LongRunningPollInterval != nil {
		in, out := &in.LongRunningPollInterval, &out.LongRunningPollInterval
		*out = new(v1.Duration)
		**out = **in
	}
	if in.StuckThreshold != nil {
		in, out := &in.StuckThreshold, &out.StuckThreshold
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DrainConfig.
func (in *DrainConfig) DeepCopy() *DrainConfig {
	if in == nil {
		return nil
	}
	out := new(DrainConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperationsConfig) DeepCopyInto(out *OperationsConfig) {
	*out = *in
	if in.Drain != nil {
		in, out := &in.Drain, &out.Drain
		*out = new(DrainConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperationsConfig.
func (in *OperationsConfig) DeepCopy() *OperationsConfig {
	if in == nil {
		return nil
	}
	out := new(OperationsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PreferredEndpointsSpec) DeepCopyInto(out *PreferredEndpointsSpec) {
	*out = *in
	if in.AdditionalEndpoints != nil {
		in, out := &in.AdditionalEndpoints, &out.AdditionalEndpoints
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PreferredEndpointsSpec.
func (in *PreferredEndpointsSpec) DeepCopy() *PreferredEndpointsSpec {
	if in == nil {
		return nil
	}
	out := new(PreferredEndpointsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuotaStatus) DeepCopyInto(out *QuotaStatus) {
	*out = *in
	if in.Used != nil {
		in, out := &in.Used, &out.Used
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.Limit != nil {
		in, out := &in.Limit, &out.Limit
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuotaStatus.
func (in *QuotaStatus) DeepCopy() *QuotaStatus {
	if in == nil {
		return nil
	}
	out := new(QuotaStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3Bucket) DeepCopyInto(out *S3Bucket) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3Bucket.
func (in *S3Bucket) DeepCopy() *S3Bucket {
	if in == nil {
		return nil
	}
	out := new(S3Bucket)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *S3Bucket) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3BucketList) DeepCopyInto(out *S3BucketList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]S3Bucket, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3BucketList.
func (in *S3BucketList) DeepCopy() *S3BucketList {
	if in == nil {
		return nil
	}
	out := new(S3BucketList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *S3BucketList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3BucketSpec) DeepCopyInto(out *S3BucketSpec) {
	*out = *in
	if in.BucketName != nil {
		in, out := &in.BucketName, &out.BucketName
		*out = new(string)
		**out = **in
	}
	if in.RetentionInDays != nil {
		in, out := &in.RetentionInDays, &out.RetentionInDays
		*out = new(int32)
		**out = **in
	}
	out.S3TenantRef = in.S3TenantRef
	if in.DrainPollInterval != nil {
		in, out := &in.DrainPollInterval, &out.DrainPollInterval
		*out = new(v1.Duration)
		**out = **in
	}
	if in.DrainStuckThreshold != nil {
		in, out := &in.DrainStuckThreshold, &out.DrainStuckThreshold
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3BucketSpec.
func (in *S3BucketSpec) DeepCopy() *S3BucketSpec {
	if in == nil {
		return nil
	}
	out := new(S3BucketSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3BucketStatus) DeepCopyInto(out *S3BucketStatus) {
	*out = *in
	in.BucketUsage.DeepCopyInto(&out.BucketUsage)
	if in.S3AdminKeysSecretRef != nil {
		in, out := &in.S3AdminKeysSecretRef, &out.S3AdminKeysSecretRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.S3EndpointConfig != nil {
		in, out := &in.S3EndpointConfig, &out.S3EndpointConfig
		*out = new(S3EndpointConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.DrainStatus != nil {
		in, out := &in.DrainStatus, &out.DrainStatus
		*out = new(BucketDrainStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3BucketStatus.
func (in *S3BucketStatus) DeepCopy() *S3BucketStatus {
	if in == nil {
		return nil
	}
	out := new(S3BucketStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3EndpointConfig) DeepCopyInto(out *S3EndpointConfig) {
	*out = *in
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PathStyleAccess != nil {
		in, out := &in.PathStyleAccess, &out.PathStyleAccess
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3EndpointConfig.
func (in *S3EndpointConfig) DeepCopy() *S3EndpointConfig {
	if in == nil {
		return nil
	}
	out := new(S3EndpointConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3Tenant) DeepCopyInto(out *S3Tenant) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3Tenant.
func (in *S3Tenant) DeepCopy() *S3Tenant {
	if in == nil {
		return nil
	}
	out := new(S3Tenant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *S3Tenant) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3TenantAccount) DeepCopyInto(out *S3TenantAccount) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3TenantAccount.
func (in *S3TenantAccount) DeepCopy() *S3TenantAccount {
	if in == nil {
		return nil
	}
	out := new(S3TenantAccount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *S3TenantAccount) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3TenantAccountList) DeepCopyInto(out *S3TenantAccountList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]S3TenantAccount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3TenantAccountList.
func (in *S3TenantAccountList) DeepCopy() *S3TenantAccountList {
	if in == nil {
		return nil
	}
	out := new(S3TenantAccountList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *S3TenantAccountList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3TenantAccountSpec) DeepCopyInto(out *S3TenantAccountSpec) {
	*out = *in
	if in.Features != nil {
		in, out := &in.Features, &out.Features
		*out = new(S3TenantFeatures)
		(*in).DeepCopyInto(*out)
	}
	if in.S3TenantRef != nil {
		in, out := &in.S3TenantRef, &out.S3TenantRef
		*out = new(corev1.ObjectReference)
		**out = **in
	}
	if in.RootSecretRef != nil {
		in, out := &in.RootSecretRef, &out.RootSecretRef
		*out = new(corev1.ObjectReference)
		**out = **in
	}
	if in.TenantDeletionPolicy != nil {
		in, out := &in.TenantDeletionPolicy, &out.TenantDeletionPolicy
		*out = new(TenantDeletionPolicy)
		(*in).DeepCopyInto(*out)
	}
	in.CommonTenantSpec.DeepCopyInto(&out.CommonTenantSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3TenantAccountSpec.
func (in *S3TenantAccountSpec) DeepCopy() *S3TenantAccountSpec {
	if in == nil {
		return nil
	}
	out := new(S3TenantAccountSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3TenantAccountStatus) DeepCopyInto(out *S3TenantAccountStatus) {
	*out = *in
	in.CommonTenantStatus.DeepCopyInto(&out.CommonTenantStatus)
	if in.S3TenantRef != nil {
		in, out := &in.S3TenantRef, &out.S3TenantRef
		*out = new(corev1.ObjectReference)
		**out = **in
	}
	if in.ObservedTenantBackendName != nil {
		in, out := &in.ObservedTenantBackendName, &out.ObservedTenantBackendName
		*out = new(string)
		**out = **in
	}
	if in.DesiredTenantBackendName != nil {
		in, out := &in.DesiredTenantBackendName, &out.DesiredTenantBackendName
		*out = new(string)
		**out = **in
	}
	if in.DeletionTimestamp != nil {
		in, out := &in.DeletionTimestamp, &out.DeletionTimestamp
		*out = (*in).DeepCopy()
	}
	if in.RootSecretRef != nil {
		in, out := &in.RootSecretRef, &out.RootSecretRef
		*out = new(corev1.ObjectReference)
		**out = **in
	}
	if in.TenantDeletionPolicy != nil {
		in, out := &in.TenantDeletionPolicy, &out.TenantDeletionPolicy
		*out = new(TenantDeletionPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3TenantAccountStatus.
func (in *S3TenantAccountStatus) DeepCopy() *S3TenantAccountStatus {
	if in == nil {
		return nil
	}
	out := new(S3TenantAccountStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3TenantClass) DeepCopyInto(out *S3TenantClass) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3TenantClass.
func (in *S3TenantClass) DeepCopy() *S3TenantClass {
	if in == nil {
		return nil
	}
	out := new(S3TenantClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *S3TenantClass) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3TenantClassList) DeepCopyInto(out *S3TenantClassList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]S3TenantClass, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3TenantClassList.
func (in *S3TenantClassList) DeepCopy() *S3TenantClassList {
	if in == nil {
		return nil
	}
	out := new(S3TenantClassList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *S3TenantClassList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3TenantClassSpec) DeepCopyInto(out *S3TenantClassSpec) {
	*out = *in
	out.StorageGridRef = in.StorageGridRef
	if in.RefreshInterval != nil {
		in, out := &in.RefreshInterval, &out.RefreshInterval
		*out = new(v1.Duration)
		**out = **in
	}
	if in.PreferredEndpoints != nil {
		in, out := &in.PreferredEndpoints, &out.PreferredEndpoints
		*out = new(PreferredEndpointsSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3TenantClassSpec.
func (in *S3TenantClassSpec) DeepCopy() *S3TenantClassSpec {
	if in == nil {
		return nil
	}
	out := new(S3TenantClassSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3TenantClassStatus) DeepCopyInto(out *S3TenantClassStatus) {
	*out = *in
	if in.S3TenantIDs != nil {
		in, out := &in.S3TenantIDs, &out.S3TenantIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.S3EndpointConfig != nil {
		in, out := &in.S3EndpointConfig, &out.S3EndpointConfig
		*out = new(S3EndpointConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.LastUpdated.DeepCopyInto(&out.LastUpdated)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3TenantClassStatus.
func (in *S3TenantClassStatus) DeepCopy() *S3TenantClassStatus {
	if in == nil {
		return nil
	}
	out := new(S3TenantClassStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3TenantFeatures) DeepCopyInto(out *S3TenantFeatures) {
	*out = *in
	if in.CustomIdentitySource != nil {
		in, out := &in.CustomIdentitySource, &out.CustomIdentitySource
		*out = new(bool)
		**out = **in
	}
	if in.PlatformServices != nil {
		in, out := &in.PlatformServices, &out.PlatformServices
		*out = new(bool)
		**out = **in
	}
	if in.SelectObjectContent != nil {
		in, out := &in.SelectObjectContent, &out.SelectObjectContent
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3TenantFeatures.
func (in *S3TenantFeatures) DeepCopy() *S3TenantFeatures {
	if in == nil {
		return nil
	}
	out := new(S3TenantFeatures)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3TenantList) DeepCopyInto(out *S3TenantList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]S3Tenant, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3TenantList.
func (in *S3TenantList) DeepCopy() *S3TenantList {
	if in == nil {
		return nil
	}
	out := new(S3TenantList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *S3TenantList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3TenantSpec) DeepCopyInto(out *S3TenantSpec) {
	*out = *in
	in.CommonTenantSpec.DeepCopyInto(&out.CommonTenantSpec)
	if in.S3TenantAccountRef != nil {
		in, out := &in.S3TenantAccountRef, &out.S3TenantAccountRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3TenantSpec.
func (in *S3TenantSpec) DeepCopy() *S3TenantSpec {
	if in == nil {
		return nil
	}
	out := new(S3TenantSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3TenantStatus) DeepCopyInto(out *S3TenantStatus) {
	*out = *in
	if in.LinkedBuckets != nil {
		in, out := &in.LinkedBuckets, &out.LinkedBuckets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.S3TenantAccountRef != nil {
		in, out := &in.S3TenantAccountRef, &out.S3TenantAccountRef
		*out = new(corev1.ObjectReference)
		**out = **in
	}
	in.CommonTenantStatus.DeepCopyInto(&out.CommonTenantStatus)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3TenantStatus.
func (in *S3TenantStatus) DeepCopy() *S3TenantStatus {
	if in == nil {
		return nil
	}
	out := new(S3TenantStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageGrid) DeepCopyInto(out *StorageGrid) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageGrid.
func (in *StorageGrid) DeepCopy() *StorageGrid {
	if in == nil {
		return nil
	}
	out := new(StorageGrid)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StorageGrid) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageGridList) DeepCopyInto(out *StorageGridList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StorageGrid, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageGridList.
func (in *StorageGridList) DeepCopy() *StorageGridList {
	if in == nil {
		return nil
	}
	out := new(StorageGridList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StorageGridList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageGridSpec) DeepCopyInto(out *StorageGridSpec) {
	*out = *in
	out.SecretRef = in.SecretRef
	if in.DefaultTenantDeletionPolicy != nil {
		in, out := &in.DefaultTenantDeletionPolicy, &out.DefaultTenantDeletionPolicy
		*out = new(TenantDeletionPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.Operations != nil {
		in, out := &in.Operations, &out.Operations
		*out = new(OperationsConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageGridSpec.
func (in *StorageGridSpec) DeepCopy() *StorageGridSpec {
	if in == nil {
		return nil
	}
	out := new(StorageGridSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageGridStatus) DeepCopyInto(out *StorageGridStatus) {
	*out = *in
	if in.Regions != nil {
		in, out := &in.Regions, &out.Regions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DefaultTenantDeletionPolicy != nil {
		in, out := &in.DefaultTenantDeletionPolicy, &out.DefaultTenantDeletionPolicy
		*out = new(TenantDeletionPolicy)
		(*in).DeepCopyInto(*out)
	}
	out.StorageGridUsage = in.StorageGridUsage
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageGridStatus.
func (in *StorageGridStatus) DeepCopy() *StorageGridStatus {
	if in == nil {
		return nil
	}
	out := new(StorageGridStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageGridUsage) DeepCopyInto(out *StorageGridUsage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageGridUsage.
func (in *StorageGridUsage) DeepCopy() *StorageGridUsage {
	if in == nil {
		return nil
	}
	out := new(StorageGridUsage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantDeletionPolicy) DeepCopyInto(out *TenantDeletionPolicy) {
	*out = *in
	if in.RetentionDuration != nil {
		in, out := &in.RetentionDuration, &out.RetentionDuration
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantDeletionPolicy.
func (in *TenantDeletionPolicy) DeepCopy() *TenantDeletionPolicy {
	if in == nil {
		return nil
	}
	out := new(TenantDeletionPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantUsage) DeepCopyInto(out *TenantUsage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantUsage.
func (in *TenantUsage) DeepCopy() *TenantUsage {
	if in == nil {
		return nil
	}
	out := new(TenantUsage)
	in.DeepCopyInto(out)
	return out
}
