# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/s3.bedag.ch_s3tenants.yaml
- bases/s3.bedag.ch_storagegrids.yaml
- bases/s3.bedag.ch_s3buckets.yaml
- bases/s3.bedag.ch_s3tenantclasses.yaml
- bases/s3.bedag.ch_s3tenantaccounts.yaml
- bases/s3.bedag.ch_s3policies.yaml
- bases/s3.bedag.ch_s3accesses.yaml
- bases/s3.bedag.ch_globals3policies.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
# - path: patches/webhook_in_s3tenants.yaml
- path: patches/webhook_in_s3buckets.yaml
- path: patches/webhook_in_s3tenants.yaml
- path: patches/webhook_in_s3tenants.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
- path: patches/cainjection_in_s3buckets.yaml
- path: patches/cainjection_in_s3tenants.yaml
# - path: patches/cainjection_in_s3tenantaccounts.yaml # TODO: implement CA injection patch for S3TenantAccount CRD if required
# - path: patches/cainjection_in_storagegrids.yaml # TODO: implement CA injection patch for StorageGrid CRD if required
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# [WEBHOOK] To enable webhook, uncomment the following section
# the following config is for teaching kustomize how to do kustomization for CRDs.

configurations:
- kustomizeconfig.yaml
